config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    root to: "members#index"
    resources :members, only: [:show, :edit, :update] do
      resources :posts, only: [:index, :destroy]
      resources :post_comments, only: [:index, :destroy]
    end
  end

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  
  # ゲストログイン機能用
  devise_scope :member do
    get "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  scope module: :public do
    root "homes#top"
    get "homes/guideline" => "homes#guideline"
    get "search_tag" => "posts#search_tag"
    get "search" => "searches#search"
    resources :members, only: [:show, :edit, :update] do
      get :favorites, on: :collection
      get "leave", on: :member
      patch "withdrawal", on: :member
        resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image
  
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  validates :name, length: { minimum: 1, maximum: 15 }
  validates :introduction, length: { maximum: 150 }
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @member = Member.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @member = Member.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @member = Member.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @member = Member.where("name LIKE?","%#{word}%")
    else
      @member = Member.all
    end
  end
  
  def active_for_authentication?
    super && (is_deleted == false)  # is_deletedがfalseならtrueを返すようにする
  end
  
  # ゲストログイン機能
  GUEST_MEMBER_EMAIL = "guest@example.com"
  def self.guest
    find_or_create_by!(email: "guest@example.com") do |member|
      member.password = SecureRandom.urlsafe_base64
      member.name = "guest"
    end
  end
  
  def guest_member?
    email == GUEST_MEMBER_EMAIL
  end
  
  # フォローした時の処理
  def follow(member_id)
    relationships.create(followed_id: member_id)
  end
  # フォロー解除時の処理
  def unfollow(member_id)
    relationships.find_by(followed_id: member_id).destroy
  end
  # フォローしているかの判定
  def following?(member)
    followings.include?(member)
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_member, only: [:show, :edit, :update]
  
  def index
    @members = Member.all.page(params[:page]).per(20)
  end

  def show
    @member = Member.find(params[:id])
    @post = @member.posts
    @post_comment = @member.post_comments
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to admin_member_path(@member.id), flash: {success: "ユーザー情報を更新しました。"}
    else
      render :edit
    end
  end

  private

  def member_params
    params.require(:member).permit(:name, :email, :introduction, :profile_image, :is_deleted)
  end
  
  def ensure_member
    @member = Member.find(params[:id])
  end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/edit.html.erb
<div class="container my-5">

  <div class="form-group">
    <label for="profile_image">ユーザーID：</label>
    <%= @member.id %>
  </div>

  <%= form_with model: @member, url: admin_member_path(@member.id), method: :patch do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="form-group">
      <label for="profile_image">プロフィール画像</label>
      <%= f.file_field :profile_image, class: "form-control-file profile_image", accept: "image/*" %>
    </div>

    <div class="form-group">
      <label for="name">ユーザー名</label>
      <%= f.text_field :name, class: "form-control name" %>
    </div>

    <div class="form-group">
      <label for="introduction">自己紹介</label>
      <%= f.text_area :introduction, class: "form-control introduction" %>
    </div>

    <div class="form-group">
      <label for="email">メールアドレス</label>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "sample@example.com", class: "form-control email" %>
    </div>

    <div class="form-group">
      <label for="introduction">ユーザーステータス：</label>
      <%= f.radio_button :is_deleted, false %>有効　<%= f.radio_button :is_deleted, true %>退会
    </div>

    <div class="form-group">
      <%= f.submit "更新する", class: "btn btn-success rounded-pill" %>
    </div>
  <% end %>
</div>

app/views/admin/members/index.html.erb
<div class="container my-5">
  <div class="row">
    <h3 class="mx-auto">ユーザー管理</h3>
  </div>

  <table class="table mt-3">
    <thead>
      <tr>
        <th>ユーザーID</th>
        <th>ユーザー名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td>
            <%= member.id %>
          </td>
          <td>
            <% if member.profile_image.attached? %>
              <%= image_tag member.profile_image.variant(resize: "80x80"), class: "rounded-circle" %>
            <% else %>
              <%= image_tag "no_image.jpg", class: "rounded-circle", size: "80x80" %>
            <% end %>
            <%= link_to member_path(member) do %>
              <%= member.name %>
            <% end %>
          </td>
          <td>
            <%= member.email %>
          </td>
          <% if member.is_deleted == false %>
            <td class="text-success">有効</td>
          <% else %>
            <td class="text-black-50">退会</td>
          <% end %>
          <td>
            <%= link_to "詳細", admin_member_path(member), class: "btn btn-primary btn-sm rounded-pill" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row justify-content-center">
    <%= paginate @members %>
  </div>
</div>

app/views/admin/members/show.html.erb
<div class="container mt-5">
  <div class="row">
    <h3 class="mx-auto">
      <%= @member.name%>さんの登録情報詳細
    </h3>
  </div>
  
  <div class="row">
    <table class="table">
      <tr class="text-center">
        <td>ユーザーID</td>
        <td><%= @member.id %></td>
      </tr>
      <tr class="text-center">
        <td>ユーザー名</td>
        <td>
          <%= link_to member_path(@member) do %>
            <%= @member.name %>
          <% end %>
        </td>
      </tr>
      <tr class="text-center">
        <td>アイコン</td>
        <td>
          <% if @member.profile_image.attached? %>
            <%= image_tag @member.profile_image.variant(resize: "80x80"), class: "rounded-circle" %>
          <% else %>
            登録無し
          <% end %>
        </td>
      </tr>
      <tr class="text-center">
        <td>自己紹介</td>
        <td>
          <% if @member.introduction.present? %>
            <%= @member.introduction.truncate(70) %>
          <% else %>
            登録無し
          <% end %>
        </td>
      </tr>
      <tr class="text-center">
        <td>メールアドレス</td>
        <td><%= @member.email %></td>
      </tr>
      <tr class="text-center">
        <td>ユーザーステータス</td>
        <% if @member.is_deleted == false %>
          <td class="text-success">有効</td>
        <% else %>
          <td class="text-black-50">退会</td>
        <% end %>
      </tr>
    </table>
  </div>
  
  <div class="row justify-content-center">
      <%= link_to "編集する", edit_admin_member_path(@member.id), class: "btn btn-success rounded-pill" %>
  </div>
  
  <div class="row justify-content-center mt-5">
    <%= link_to admin_member_posts_path(@member.id), class: "mr-3" do %>
      <i class="far fa-images"></i>
      投稿一覧
    <% end %>
    
    <%= link_to admin_member_post_comments_path(@member.id) do  %>
      <i class="far fa-comment"></i>
      コメント一覧
    <% end %>
  </div>
</div>