config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    root to: "members#index"
    resources :members, only: [:show, :edit, :update] do
      resources :posts, only: [:index, :destroy]
      resources :post_comments, only: [:index, :destroy]
    end
  end

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  
  # ゲストログイン機能用
  devise_scope :member do
    get "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  scope module: :public do
    root "homes#top"
    get "homes/guideline" => "homes#guideline"
    get "search_tag" => "posts#search_tag"
    get "search" => "searches#search"
    resources :members, only: [:show, :edit, :update] do
      get :favorites, on: :collection
      get "leave", on: :member
      patch "withdrawal", on: :member
        resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_tag_relations, dependent: :destroy
  has_many :tags, through: :post_tag_relations
  belongs_to :member
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :image
  
  validates :body, length: { maximum: 150 } 
  validate :check_image
  
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :most_favorited, -> { 
    left_joins(:favorites)
      .group(:id)
      .order(Arel.sql('COUNT(favorites.id) DESC'))
  }

  # タグ付け機能
  def save_tag(sent_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
      current_tags = self.tags.pluck(:name) unless self.tags.nil?
      
      # 現在取得したタグから送られてきたタグを除いてoldtagとする
      old_tags = current_tags - sent_tags
      
      # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
      new_tags = sent_tags - current_tags
  
      # 古いタグを消す
      old_tags.each do |old|
        self.tags.delete　Tag.find_by(name: old)
      end
  
      # 新しいタグを保存
    new_tags.each do |new|
      if new.length <= 50
        new_post_tag = Tag.find_or_create_by(name: new)
        self.tags << new_post_tag
      end
    end
  end
  
  # お気に入り機能
  def favorited_by?(member)
    return false if member.nil? #未ログインユーザーの場合nilではなくfalseを返すようにする
    favorites.exists?(member_id: member.id)
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("theme LIKE?","#{word}")
    elsif search == "forward_match"
      @post = Post.where("theme LIKE?","#{word}%")
    elsif search == "backward_match"
      @post = Post.where("theme LIKE?","%#{word}")
    elsif search == "partial_match"
      @postk = Post.where("theme LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
  
  private

  #Active Storageのバリデーションチェック
  def check_image
    if image.attached?
      unless image.blob.content_type.start_with?('image/')
        errors.add(:image, 'は画像ファイルを選択してください）')
      else
        if image.blob.byte_size > 3.megabytes
          errors.add(:image, 'のサイズは3MB以下にしてください')
        end
      end
    else
      errors.add(:image, 'ファイルを添付してください')
    end
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @member = Member.find(params[:member_id])
    @posts = @member.posts.page(params[:page]).per(25)
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_member_posts_path(post.member), flash: {success: "投稿の削除が完了しました。"}
  end
  
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container my-5">

<div class="row mt-5 d-flex justify-content-center">
  <h3><%= @member.name %>さんの投稿一覧</h3>
</div>

<div class="row">
  <% if @posts.present? %>
    <table class="table table-striped mt-3">
      <thead>
        <tr class="text-center">
          <th>投稿ID</th>
          <th>Challenge Theme</th>
          <th>説明</th>
          <th>投稿日時</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr class="text-center">
            <td><%= post.id %></td>
            <td style="word-break: break-all;"><%= post.theme %></td>
            <td style="word-break: break-all;"><%= post.body %></td>
            <td><%= post.created_at.strftime("%Y/%m/%d %H:%M") %></td>
            <td><%= link_to "詳細", post_path(post.id), class: "btn btn-sm btn-primary" %></td>
            <td><%= link_to "削除", admin_member_post_path(@member, post), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-sm btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="col text-center">
      <%= paginate @posts %>
    </div>
  <% else %>
    <p class="mt-3">投稿はありません</p>
  <% end %>
</div>
</div>