config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    root to: "members#index"
    resources :members, only: [:show, :edit, :update] do
      resources :posts, only: [:index, :destroy]
      resources :post_comments, only: [:index, :destroy]
    end
  end

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  
  # ゲストログイン機能用
  devise_scope :member do
    get "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  scope module: :public do
    root "homes#top"
    get "homes/guideline" => "homes#guideline"
    get "search_tag" => "posts#search_tag"
    get "search" => "searches#search"
    resources :members, only: [:show, :edit, :update] do
      get :favorites, on: :collection
      get "leave", on: :member
      patch "withdrawal", on: :member
        resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :member
  belongs_to :post
  
  validates :comment, presence:true, length: { minimum: 1, maximum: 150 }
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @member = Member.find(params[:member_id])
    @post_comments = @member.post_comments.page(params[:page]).per(25)
  end
  
  def destroy
    post_comment = PostComment.find(params[:id])
    post_comment.destroy
    redirect_to admin_member_post_comments_path(post_comment.member), flash: {success: "コメントの削除が完了しました。"}
  end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/index.html.erb
 <div class="container my-5">
 
  <div class="row mt-5 d-flex justify-content-center">
    <h3><%= @member.name %>さんのコメント一覧</h3>
  </div>
  
  <div class="row justify-content-center">
    <% if @post_comments.present? %>
      <table class="table table-striped mt-3">
        <thead>
          <tr class="text-center">
            <th>コメントID</th>
            <th>コメント</th>
            <th>投稿日時</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @post_comments.each do |post_comment| %>
            <tr class="text-center">
              <td><%= post_comment.id %></td>
              <td style="word-break: break-all;"><%= post_comment.comment %></td>
              <td><%= post_comment.created_at.strftime("%Y/%m/%d %H:%M") %></td>
              <td><%= link_to "詳細", post_path(post_comment.post), class: "btn btn-sm btn-primary" %></td>
              <td><%= link_to "削除", admin_member_post_comment_path(@member, post_comment), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-sm btn-danger" %></td>
              <td></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row justify-content-center">
        <%= paginate @post_comments %>
      </div>
    <% else %>
      <p class="mt-3">コメントはありません</p>
    <% end %>
  </div>
</div>