config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    root to: "members#index"
    resources :members, only: [:show, :edit, :update] do
      resources :posts, only: [:index, :destroy]
      resources :post_comments, only: [:index, :destroy]
    end
  end

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  
  # ゲストログイン機能用
  devise_scope :member do
    get "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  scope module: :public do
    root "homes#top"
    get "homes/guideline" => "homes#guideline"
    get "search_tag" => "posts#search_tag"
    get "search" => "searches#search"
    resources :members, only: [:show, :edit, :update] do
      get :favorites, on: :collection
      get "leave", on: :member
      patch "withdrawal", on: :member
        resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only: [:new, :index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <h4><%= pluralize(model.errors.count, "error") %> prohibited this post from being saved:</h4>
    <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <p class="alert alert-<%= bootstrap_alert(key) ? bootstrap_alert(key) : key %> alert-dismissible fade show">
    <%= value %><button type="button" class="close" data-dismiss="alert">&times;</button>
  </p>
<% end %>

app/views/layouts/_search.html.erb
<%= form_with url: search_path, local: true, method: :get, class: 'form-inline' do |f| %>
  <%= f.text_field :word, class: 'form-control' , placeholder: "キーワード" %>
  <%= f.select :range, options_for_select([['ユーザー'], ['Challenge Theme'], ['タグ']]), {}, { class: 'form-control' } %>
  <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]), {}, { class: 'form-control' } %>
  <%= f.submit "検索", class: "btn btn-secondary form-control" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChallengePic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>

    <script src="https://kit.fontawesome.com/dac6d8f3a1.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//unpkg.com/jscroll/dist/jquery.jscroll.min.js"></script>
  </head>

<body>
  <header>
  <nav class="navbar navbar-expand-xl navbar-light">
    <!--ロゴ-->
    <div class="navbar-brand">
      <% if admin_signed_in? %>
        <%= link_to image_tag("logo.png", alt: "ロゴ", width: '300px'), admin_root_path %>
      <% else %>
        <%= link_to image_tag("logo.png", alt: "ロゴ", width: '300px'), "/" %>
      <% end %>
    </div>
    <!--ハンバーガーメニューアイコン-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <!--管理者ログイン時-->
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to admin_root_path, class: "nav-link head-text text-decoration-none" do %>
            <i class="fas fa-user"></i>
            ユーザー管理
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link head-text text-decoration-none" do %>
            <i class="fas fa-sign-out-alt"></i>
            ログアウト
            <% end %>
          </li>
        <!--ユーザーログイン時-->
        <% elsif member_signed_in? %>
          <li class="nav-item">
            <%= render 'layouts/search' %>
          </li>
          <li class="nav-item">
            <%= link_to posts_path, class: "nav-link head-text text-decoration-none" do %>
            <i class="far fa-images"></i>
            投稿一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_post_path, class: "nav-link head-text text-decoration-none" do %>
            <i class="fas fa-paper-plane"></i>
            投稿する
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to member_path(current_member.id), class: "nav-link head-text text-decoration-none" do %>
            <i class="fas fa-user"></i>
            マイページ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to homes_guideline_path, class: "nav-link head-text text-decoration-none" do %>
            <i class="fas fa-book"></i>
            ガイドライン
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_member_session_path, method: :delete, class: "nav-link head-text text-decoration-none" do %>
            <i class="fas fa-sign-out-alt"></i>
            ログアウト
            <% end %>
          </li>
        <!--未ログイン時-->
        <% else %>
          <li class="nav-item">
            <%= render 'layouts/search' %>
          </li>
          <li class="nav-item">
            <%= link_to posts_path, class: "nav-link head-text text-decoration-none" do %>
            <i class="far fa-images"></i>
            投稿一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_post_path, class: "nav-link head-text text-decoration-none" do %>
            <i class="fas fa-paper-plane"></i>
            投稿する
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to homes_guideline_path, class: "nav-link head-text text-decoration-none" do %>
            <i class="fas fa-book"></i>
            ガイドライン
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_member_registration_path, class: "nav-link head-text text-decoration-none" do %>
            <i class="fas fa-user-plus"></i>
            新規登録
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_member_session_path, class: "nav-link head-text text-decoration-none" do %>
            <i class="fas fa-sign-in-alt"></i>
            ログイン
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to members_guest_sign_in_path, class: "nav-link head-text text-decoration-none" do %>
            <i class="fas fa-sign-in-alt"></i>
            ゲストログイン
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>
  <main>
    <div class="flash-message text-center">
      <%= render partial: "layouts/flash" %>
    </div>
    <%= yield %>
  </main>
</body>
</html>